name: Release
on:
  workflow_dispatch:
  repository_dispatch:
    types: release
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get Version Number
        id: version
        run: |
          set -x
          npm install semver --quiet
          curl --silent "https://api.github.com/repos/$GITHUB_REPOSITORY/releases/latest" > latest.txt
          cat latest.txt
          LATEST=$(cat latest.txt | jq -r .tag_name)
          echo $LATEST
          [[ -z "$LATEST" ]] && { echo "Could not get latest version" ; exit 1; }
          echo "::set-output name=number::$(node_modules/.bin/semver -i minor $LATEST)"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.number }}
          release_name: Release ${{ steps.version.outputs.number }}
          draft: false
          prerelease: false
